name: flutter_journey
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  youtube_player_flutter: ^8.1.2
  klutter_youtube_player_iframe_plus: ^0.0.2
  web_socket_channel: ^2.4.0
  shared_preferences:
  http: ^1.2.0
  video_player: ^2.8.5
  chewie: ^1.5.0
  flick_video_player: ^0.5.0
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  sign_in_button: ^3.2.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.15.8
  cached_network_image: ^3.3.1
  image_picker: ^1.0.8
  firebase_storage: ^11.6.9
  random_string: ^2.3.1
  flex_color_scheme: ^7.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - E:/Extansion/github/flutter_journey/assets/image/
    - assets/json/
    - assets/gifs/200.webp
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Inspiration
      fonts:
        - asset: assets/fonts/Inspiration-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

