// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1xVUoGdBup4FJ3SJo5HfaujjPOBsT8jc',
    appId: '1:703829445445:web:1967bf0c00429d2ae58c2c',
    messagingSenderId: '703829445445',
    projectId: 'quizapp-c8d1a',
    authDomain: 'quizapp-c8d1a.firebaseapp.com',
    storageBucket: 'quizapp-c8d1a.appspot.com',
    measurementId: 'G-SGVHHG9MCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxKarrny6gWIInyCtlv67-s1SL9-dYexk',
    appId: '1:703829445445:android:343a91a7593e6e63e58c2c',
    messagingSenderId: '703829445445',
    projectId: 'quizapp-c8d1a',
    storageBucket: 'quizapp-c8d1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGp36WDI1K8ei03ZrvSmsANeMow4y7kxA',
    appId: '1:703829445445:ios:8f831065c1d8bf44e58c2c',
    messagingSenderId: '703829445445',
    projectId: 'quizapp-c8d1a',
    storageBucket: 'quizapp-c8d1a.appspot.com',
    iosBundleId: 'com.example.flutterJourney',
  );
}
